"""empty message

Revision ID: f4d69403d689
Revises: 7f252ce7fd47
Create Date: 2021-04-24 00:50:02.651485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4d69403d689'
down_revision = '7f252ce7fd47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('family_structure', sa.Column('age', sa.Integer(), nullable=False))
    op.add_column('family_structure', sa.Column('first_name', sa.String(length=120), nullable=False))
    op.add_column('family_structure', sa.Column('last_name', sa.String(length=120), nullable=False))
    op.add_column('family_structure', sa.Column('lucky_numbers', sa.String(length=120), nullable=False))
    op.create_unique_constraint(None, 'family_structure', ['last_name'])
    op.create_unique_constraint(None, 'family_structure', ['first_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'family_structure', type_='unique')
    op.drop_constraint(None, 'family_structure', type_='unique')
    op.drop_column('family_structure', 'lucky_numbers')
    op.drop_column('family_structure', 'last_name')
    op.drop_column('family_structure', 'first_name')
    op.drop_column('family_structure', 'age')
    # ### end Alembic commands ###
